---
title: "2_Workflow: basics"
format: html
editor: visual
---

## **2  Workflow: basics**

**2.1 Coding basics**

All R statements where you create objects, **assignment** statements, have the same form:

object_name\<-value

When reading that code, say \"object name gets value\" in your head.

\<-   keyboard shortcut: Alt + - (the minus sign)

Notice that RStudio automatically surrounds \<- with spaces, which is a good code formatting practice. Code can be miserable to read on a good day, so giveyoureyesabreak and use spaces.

**2.2 Comments**

R will ignore any text after \# for that line. to write **comments**

Use comments to explain the **why** of your code, not the how or the what. The what and how of your code are always possible to figure out, even if it might be tedious, by carefully reading it. If you describe every step in the comments, and then change the code, you will have to remember to update the comments as well or it will be confusing when you return to your code in the future.

For data analysis code, use comments to explain your overall plan of attack and record important insights as you encounter them. There\'s no way to re-capture this knowledge from the code itself.

**2.3 What\'s in a name?**

Object names must start with a letter and can only contain letters, numbers, \_, and .. You want your object names to be descriptive, so you\'ll need to adopt a convention for multiple words. We recommend **snake_case**, where you separate lowercase words with \_.

i_use_snake_case

otherPeopleUseCamelCase

some.people.use.periods

And_aFew.People_RENOUNCEconvention

you can press ↑ to bring the last command you typed and edit it.

Or, type \"first letters of object\" then press Cmd/Ctrl + ↑ to list all the commands you\'ve typed that start with those letters. Use the arrow keys to navigate, then press enter to retype the command.

**2.4 Calling functions**

When you\'ve selected the function you want, press TAB again. RStudio will add matching opening (() and closing ()) parentheses for you.

**Keyboard Shortcut**

Press Option + Shift + K   /     Alt + Shift + K.
